### ISSUE TITLE
Documentation on response data

### ISSUE THREAD

**Issue by commandodev** [nhost/nhost-js-sdk#12]
Hey there,

I'm writing purescript bindings to this package. Would it be possible to have the `login`, `register` and any other relevant auth commands return the response data (as well as having documentation for what fields are available)?

E.g. Here:

https://github.com/nhost/nhost-js-sdk/blob/master/src/auth.js#L202
https://github.com/nhost/nhost-js-sdk/blob/master/src/auth.js#L241 (would be nice to have the data returned after doing init session)

It might also be nice to have some notion of getting a current user profile or something (unless that's something you would hit hasura for normally)?

**Comment by nunopato** [comment]
@commandodev `v3.0.0` (https://github.com/nhost/nhost-js-sdk/releases/tag/v3.0.0) addresses all of your concerns. Closing the issue.
