### ISSUE TITLE
Upgrade error message legibility

### ISSUE THREAD

**Issue by Svarto** [nhost/nhost-js-sdk#17]
Right now the login and register functions return the standard axios errors, and if you want the messages from the errors you have to drill down into the promise returned error like so:

              auth
                .register(email, password)
                .catch((e) => {
                  alert(e.response.data.message);
                });

Could we simplify this and also clean up the error response to be something more legible, perhaps even customizable?

**Comment by elitan** [comment]
I think this needs to ba taken care of on the client/app level. 

For your example above, if you don't have network connectivity, that code won't work since you won't get a response.
