### ISSUE TITLE
use jwt-decode rather than jsonwebtoken

### ISSUE THREAD

**Issue by mnlbox** [nhost/nhost-js-sdk#2]
Hi @elitan ,
As `jsonwebtoken` package didn't work in React-Native and it seems that you are only need jwt decode capability please switch `jsonwebtoken` to `jwt-decode` package then we can use nhost in React-Native mobile app more simpler.
https://github.com/auth0/jwt-decode

**Comment by thangngoc89** [comment]
also, jsonwebtoken is huge in size
