### ISSUE TITLE
[FEATURE REQUEST] - Use jwt_expires_in to override refresh_interval_time

### ISSUE THREAD

**Issue by go4cas** [nhost/nhost-js-sdk#28]
Once a user has been successfully logged in, using the `login()` method, the nhost API will include the `jwt_expires_in` in the response payload. If this is used, to override the default of the `refresh_interval_time` in the SDK config, the client and nhost will be closer aligned.

**Comment by elitan** [comment]
Came down to

```js
      const refresh_interval_time =
        this.refresh_interval_time !== null ||
        typeof jwt_expires_in !== "number"
          ? this.refresh_interval_time
          : Math.max(30 * 1000, jwt_expires_in - 10000);
```

So. if `refresh_interval_time` is set in the config, that one is used.

Otherwise, the `jwt_expires_in` value will be used (-10 seconds). But the end value will never be lower than 30 seconds.

**Comment by elitan** [comment]
fixed in https://github.com/nhost/nhost-js-sdk/commit/bbd5d5579369443ecd5c077cabcc7ca675d52181
