### ISSUE TITLE
Use 100% js implementation of Blob

### ISSUE THREAD

**Issue by elitan** [nhost/nhost-js-sdk#35]
if possible.

**Comment by stephen776** [comment]
Piggybacking on this...

I believe release 2.2.4 is broken running in a react-native expo app.

I get error building the JS bundle stating that “module” cannot be loaded from esm.js

Reverting to 2.2.3 resolves the issue.

**Comment by scastiel** [comment]
@stephen776 I had an error with ESM and Blob too, but not with React Native, just using Parcel instead of Create-React-App. Same, reverting to 2.2.3 resolved my issue.

**Comment by Svarto** [comment]
+1
