### ISSUE TITLE
Error when importing nhost-js-sdk in react-native

### ISSUE THREAD

**Issue by ewal** [nhost/nhost-js-sdk#38]
I'm trying to configure auth in an Expo (v.39.0.2) project but am running into issues when importing the nhost-js-sdk package. See picture below. The `esm` module do exists in the node_modules folder and I've tried the instructions several times. 
Any ideas? Looks like a dependency on the `blob` package.

![nhost_error](https://user-images.githubusercontent.com/676873/99180869-631eba80-272a-11eb-8e8b-142b9c97d464.jpg)

**Comment by ewal** [comment]
@Svarto, I saw your comment here https://github.com/amitport/blob/issues/1 on the issue. Did you ever find a solution?

**Comment by ewal** [comment]
Forked and did a revert on this commit https://github.com/nhost/nhost-js-sdk/commit/42ff55341ddb57cf81f91b12c7051580c381a409#diff-08439db99ca5cff201905a1513b3b78132bb333a135ac23e990ac84a423975f7 and it now works for me.

**Comment by Svarto** [comment]
Nice revert! I didn't find a solution, stuck with the old sdk version but I saw that this was flagged in react native repository so I think a fix might be coming.

**Comment by elitan** [comment]
Could you try this: https://github.com/nhost/nhost-js-sdk/pull/44

`npm install git://github.com:nhost/nhost-js-sdk.git#new-blob-pkg`

**Comment by emilkarl** [comment]
Wey! 🙌
