### ISSUE TITLE
save refresh token to cookie instead of localStorage

### ISSUE THREAD

**Issue by vgrafe** [nhost/nhost-js-sdk#4]
As explained in [Hasura's blog post about JWTs](https://blog.hasura.io/best-practices-of-using-jwt-with-graphql/#refresh_token_persistance), it seems preferable to store the refresh token in a cookie rather than localStorage.

Let me know if you need help on this.

**Comment by vgrafe** [comment]
just saw that you persist the JWT in sessionStorage... this is beyond my knowledge security-wise. I'll trust your experience here!

**Comment by vgrafe** [comment]
Alright (and sorry for the spam!), I knew something was bothering me about this. Using cookies (in my case, via js-cookie) allows better support for Nextjs and probably other SSR-friendly frameworks. I have a working example locally, it is too early to publish (playground mess!) but let me know if you wanna have a look.

**Comment by elitan** [comment]
Thanks for the input.

Are you currently developing an SSR-app that's going to use Nhost for authentication and storage? if so, why did you chose a SSR framework instead of SPA (ex, `create-react-app`)?

I want to have a look, I need to learn more about this.

**Comment by elitan** [comment]
Also, how do you store the JWT token in a SSR application?

**Comment by vgrafe** [comment]
I am playing around with nextjs and trying to make it play well with auth and data fetching. Storage should be trivial to implement. 
Using cookies to store the token is recommended [here](https://spectrum.chat/next-js/general/how-to-use-jwt-in-an-authentication-system-using-next-js~e62f1e68-3939-49f8-aac5-65f15f755daa?m=MTU2MDU4MDE0MTU4Nw==) and [there](https://medium.com/@anMagpie/next-js-jwt-auth-example-app-4ea4d7f49fa3).

Not an expert on this topic, but SSR with nextjs worked out of the box when I moved all data persistence to cookies.

**Comment by hardcash** [comment]
I'm not sure about using Cookies. Maybe if there could be a different sdk for mobile? Cookie API on React Native is notably unreliable, known to cause sign-out issues, invalid cookies, etc. I would prefer to use Asyn/localStorage as I could swap them out easily when working with React Native Web and avoid these issues.

**Comment by vgrafe** [comment]
There are security concerns with localStorage on web. Another solution to cookies is to store the token in-memory.

**Comment by elitan** [comment]
In the next version of the sdk/hasura-backend-plus the refresh token will be stored as a httpOnly cookie and the jwt token will be stored in memory.

**Comment by elitan** [comment]
Done

**Comment by elitan** [comment]
Ok. Did a lot of research on this now. 

There are two big solutions.

1. localStorage
Store all tokens in localStorage. Vulnerable if your app is vulnerable to XSS.

2. Cookies
Store all tokens as http only cookies. We can not do that, we need the JWT token on the client to send GraphQL requests (Authorizatoin header).

To just do some tokens as http only cookies does not make a lot of sense to me. We still store the JWT in memory client side, which will be vulnerable to XSS.

Using cookies comes with other cons, such as some users/browsers has third party cookies turned of by default. So if your backend runs on another domain (backend-xxx.nhost.io) than your app (myapp.com) things wont work.

Conclusion:
We will go back to `localStorage` and be vulnerable to XSS. 

*But that is horrible! XSS?!?!?!?*
Yes and No. React, Vue and other frontend frameworks does a great job protecting against XSS. Make sure you read up on XSS on your particular framework to be safe from XSS.

**Comment by defrex** [comment]
Unfortunately, localStorage still leaves out SSR.

**Comment by elitan** [comment]
> Unfortunately, localStorage still leaves out SSR.

I'm not sure it does any more than using the cookie strategy does. 

I don't think building a web app based on SSR (Server Side Rendering) is a good idea. SSR is, in my opinion, for building landing pages. Not web apps.

**Comment by defrex** [comment]
IMO, for a landing page, you're usually better off static rendering, rather than server-side rendering. Though, the lines between landing pages and web apps aren't always so clean. How would you classify a directory site like Yelp, or a social site like Reddit? Are those landing pages or web apps? Do you think client-rendering would deliver the best experience? 🤔 

Server-side rendering in web apps is a massive performance boost from the user's perspective. I've been using it for years, on a variety of projects, with nothing but satisfaction. Not only me! The community at large continues to embrace SSR more all the time, especially now that frameworks like Next.js are making it easy (and on by default).

It strikes me as the wrong hill to die on when you're trying to start a GraphQL company, if I may say.

**Comment by elitan** [comment]
@defrex You're right. When I see SSR I think about static rendering. 

I'll make sure to research this better. 👍
