### ISSUE TITLE
Uncaught TypeError: dist.initializeApp is not a function

### ISSUE THREAD

**Issue by beebase** [nhost/nhost-js-sdk#42]
I'm trying to setup a client with Svelte but I'm getting this error in the browser.
Is there anything I'm missing?

```
nhost.js:7 Uncaught TypeError: dist.initializeApp is not a function
    at nhost.js:7
```

**nhost.js**
```
import nhost from "nhost-js-sdk"

const config = {
  base_url: "http://localhost:8080/v1/graphql",
}

nhost.initializeApp(config)

const auth = nhost.auth()
const storage = nhost.storage()

export { auth, storage }
```

**App.svelte**
```
<script>
  ....
  import { auth } from "@/js/nhost";
</script>
```

**Comment by elitan** [comment]
Hmm, I'm not experienced in Svelt but I see some potential errors:

- `base_url` should not point to the graphql url. It should instead point to the HBP (Hasura Backend Plus) URL.
- It looks strange that you get `Uncaught TypeError: **dist**.initializeApp`. Why `dist` and not `nhost`?

**Comment by beebase** [comment]
> * `base_url` should not point to the graphql url. It should instead point to the HBP (Hasura Backend Plus) URL.

So that should be localhost:3000 ?
(I'm running everything in a local docker container on my laptop)

In the meantime I'll try connecting with another client framework.
Maybe the Svelte bundler (rollup)  is messing up stuff.
Backend is working fine btw. Did some api calls with postman.
```
localhost:3000/auth/register
.../login 
etc.
```

**Comment by beebase** [comment]
I just did a Svelte build with snowpack, which works fine.

BTW: this is a great package!
So cool not having to write authentication code anymore 😃
