### ISSUE TITLE
[question] query user info after login?

### ISSUE THREAD

**Issue by beebase** [nhost/nhost-js-sdk#46]
After login do you have to query the user info with the given email input, or are there other ways to do this?

**Comment by elitan** [comment]
Yes

Ex: 

```js
const GET_SELF = gql`
  query getSelf($user_id: uuid!) {
    me: users_by_pk(id: $user_id) {
      id
      display_name
      account {
        id
        email
      }
    }
  }
`;

  const { loading, error, data } = useQuery(GET_SELF, {
    variables: {
      user_id: auth.getClaim("x-hasura-user-id"),
    },
    context: {
      headers: {
        "x-hasura-role": "me",
      },
    },
  });
```

From https://github.com/nhost-examples/nextjs-apollo

More specifically: https://github.com/nhost-examples/nextjs-apollo/blob/main/components/app/layout/header.jsx

**Comment by beebase** [comment]
That is cool.
I was decoding the JWT token in order to get user id etc. but the  "me" role and auth.getClaim("...") are a much easier way.
(must have overlooked that in the docs. I'm also a bit new to JWT)
Thanks for the info.👍
