### ISSUE TITLE
onAuthStateChanged can be mistakenly overriden

### ISSUE THREAD

**Issue by vgrafe** [nhost/nhost-js-sdk#5]
The current logic seems to allow setting only one callback; setting a new one replaces the former one.

**Comment by elitan** [comment]
"it's not a bug, it's a feature!" ;)

No but seriously. Could you describe a use case where the current implementation could be a problem?

**Comment by vgrafe** [comment]
I think it is generally a risk to uninformed users, who might want to directly bind this callback at multiple places within their app.

**Comment by elitan** [comment]
I agree. You should be able to set up multiple `onAuthStateChanged` callback and they should not override.

**Comment by defrex** [comment]
If you're getting in there, ideally it returns a function to remove the listener so you can clean them up consistently. This is especially important when used in `useEffect`, which I presume will be a common place to use them.

**Comment by elitan** [comment]
Fixed. New functions get added independently.
