### ISSUE TITLE
Use promises for isAuthenticated()

### ISSUE THREAD

**Issue by MarcelloTheArcane** [nhost/nhost-js-sdk#52]
Currently, using `auth.isAuthenticated()` returns:

> - `true` means users is logged in
> - `false` means users is not logged in
> - `null` means that nhost-js-sdk is trying to login the user, but don't know yet if the user is logged in or not.

[Source](https://docs.nhost.io/libraries/nhost-js-sdk#:~:text=Check%20if%20user%20is%20authenticated)

It would be better I think if instead of returning `null`, it returned a promise which eventually resolved to either `true` or `false`.

---

Usecase:

I'm using the Vue router, which can have a `beforeEach` navigation guard:

```js
router.beforeEach((to, _, next) => {
  console.log(auth.isAuthenticated())
  if (!auth.isAuthenticated() && to.meta.auth) {
    next({ name: 'login' })
  } else {
    next()
  }
})
```

If I refresh the page, `auth.isAuthenticated()` returns null, and then eventually `true` - however by this point it's redirected to the login page.

I could use `await auth.isAuthenticated()` if it returned a promise, which would solve the issue.

**Comment by Svarto** [comment]
The way I manage it is that null shows a loading screen (the initial app loading screen for my app, I am using RN). Then the user is only navigated to the login screen if the auth.isAuthenticated is false.

-------- Original Message --------

**Comment by MarcelloTheArcane** [comment]
Hello @Svarto, thanks for replying so quickly!

I'm not sure how I'd do that with router guards though - do you use that in Vue?

I suppose I could simply use page-by-page authentication checks, but that seems like a lot of repetition.

**Comment by Svarto** [comment]
Hmm, i have no experience with Vue. In React I basically just do a conditional route, if it is null then show the loading screen, if false then login and if true then show the app main screen.

Then I have the auth.onAuthenticationChange subscribed to and if it switches then it throws the user back to the login screen.

Maybe that helps? Otherwise you'll have to wait for someone with some Vue experience, unfortunately I can't help you there

-------- Original Message --------

**Comment by MarcelloTheArcane** [comment]
Okay thanks for the tips, I'll see if there is anything comparable for Vue.

Thinking about it, it would be nice if everything was promise-based, for example `auth.getJWTToken()`.

Is that something v3 could address?

**Comment by nunopato** [comment]
@MarcelloTheArcane I am not sure that would fix your issue. The code for `isAuthenticated` is not async because it immediately returns true, false, or null. Using a promise instead would have similar behavior, it wouldn't guarantee to wait until it knows whether the user is logged in or not. We are actually improving a few things for v3.0, so I will come back to you on this soon.

**Comment by MarcelloTheArcane** [comment]
@nunopato Yes, I did have a quick look and I reckon it would need quite a big refactor to manage 🙁 

I suppose in the meantime I could try to make my own SDK, but this one is so convenient!

I wonder what would happen if I wrapped it all in a `setTimeout` for 0 seconds - pushing it to the back of the stack?

**Comment by elitan** [comment]
@MarcelloTheArcane `isAuthenticated()` works well with `onAuthStateChanged()` described in the docs [here](https://docs.nhost.io/libraries/nhost-js-sdk#usage).

To register a callback to run when the auth state changes (e.g., when a user logs out) is done via onAuthStateChanged().

```js
auth.onAuthStateChanged((loggedIn) => {
  console.log("auth state changed!");
  console.log({ loggedIn });
});
```

`onAuthStateChanged` will trigger everytime the auth state changes from `null`, `true`, `false`.

I don't know how to implement this in Vue/NuxtJS but this is how we use it in React: https://github.com/nhost/react-auth/blob/master/src/index.js

**Comment by MarcelloTheArcane** [comment]
Thanks @elitan.  I actually made a simple promise-based SDK - https://gist.github.com/MarcelloTheArcane/ce0b3bf2efa2d0b23de3812ab1bf692e

It seems to work with the Vue router guards.

**Comment by nunopato** [comment]
@MarcelloTheArcane glad you have it sorted out, we will have some example apps for Vue/NuxtJS soon. Feel free to close the issue if there aren't any remaining issues for you.

**Comment by MarcelloTheArcane** [comment]
I'd really like to see promises in the official SDK, but can close if that's not the direction you would like to take.

**Comment by elitan** [comment]
> I'd really like to see promises in the official SDK, but can close if that's not the direction you would like to take.

I talked with a NuxtJS developer last week and I now understand why you'd want that. It might come soon :)
