### ISSUE TITLE
Call refreshToken when JWTExpired error

### ISSUE THREAD

**Issue by RubenVanEldik** [nhost/nhost-js-sdk#54]
Hi!

I'm building out my frontend and everything is working smoothly, as long as the user stays logged in and active the tokens get refreshed automatically,  but sometimes the user has been inactive for too long and when they make a GraphQL request via Apollo they get a JWTExpired back. This is expected, but I would like to add an onError method (with apollo-link-error) to refresh the JWT and make the query again.

In the source code I see that there is a refreshToken method, but it's private, so I can't call it. What's the best way to manually refresh a token?

**Comment by nunopato** [comment]
@RubenVanEldik sorry for only now getting back to you. Since v3.0.0 you can call `refreshSession()`. Please scroll-down to the bottom here within the release notes https://github.com/nhost/nhost-js-sdk/releases/tag/v3.0.0

**Comment by RubenVanEldik** [comment]
Wow, amazing! 😃 

V3.0.0. fixes everything that I could think of!

1. Option to manually refresh the token
2. No automatic logout when the server doesn't respond with a 401 status. (e.g. no internet connection)
3. An object parameter for login, logout, etc.

Again, amazing work @nunopato and @elitan!
