### ISSUE TITLE
Refresh lock seems to not work

### ISSUE THREAD

**Issue by RubenVanEldik** [nhost/nhost-js-sdk#66]
I am using nhost-js-sdk 3.0.0, but the refresh lock does not seem to work. 

https://github.com/nhost/nhost-js-sdk/blob/43c0934a9e61b7dcae4d80d6f490d38796a74649/src/Auth.ts#L559-L563

Sometimes the refreshSession gets called twice, the second one obviously fails, thereby automatically logging the user out. Do others experience the same problem?

**Comment by Svarto** [comment]
this is fixed in 3.1.0

**Comment by RubenVanEldik** [comment]
Oh, wow! Awesome! 🥳

**Comment by qpre** [comment]
I’m gettting this behaviour again in 3.1.1

**Comment by Svarto** [comment]
Same here

**Comment by larssbr** [comment]
Same here

**Comment by elitan** [comment]
I'd suggest going back to 3.1.0 (3.1.1 is a pre-release). 

All of our focus goes into Nhost v2 with new SDKs where this is addressed.
