### ISSUE TITLE
Local authentication functions such as login and register don't work

### ISSUE THREAD

**Issue by frissonlabs** [nhost/nhost-js-sdk#7]
Local authentication functions such as login and register don't work, most likely due to the introduction of oAuth authentication. Login and register endpoints need to be updated

**Comment by elitan** [comment]
nhost-js-sdk will be update to match the latest updates in hasura-backend-plus (HBP).

The new endpoints in HBP is:

```
/auth/local/register
/auth/local/login
```

So if you have updated to tha latest master branch of HBP this nhost-js-sdk should work.

This will be in effect at Nhost this week.

**Comment by elitan** [comment]
Did you get it to work @frissonlabs ?
