### ISSUE TITLE
change password endpoint response

### ISSUE THREAD

**Issue by cezarneaga** [nhost/nhost-js-sdk#71]
Hi there,

in case the existing password is wrong the error should be specific not generic.
could we send these through somehow?

thanks,
C

**Comment by elitan** [comment]
It's being discussed here: https://github.com/nhost/hasura-backend-plus/issues/270. I'll close this one for now.

**Comment by cezarneaga** [comment]
i think that is too big of a conversation to wrap this in. 
here the user is already logged in. there is no security concern.

**Comment by elitan** [comment]
Oh sorry. I was too quick. I'll re-open.

**Comment by cezarneaga** [comment]
'Incorrect current password.' is fine. just let it pass through. :)
there is also min length validations. which i dont see in that file but they should come too

**Comment by cezarneaga** [comment]
closed and solution is explained in #78
