### ISSUE TITLE
AUTO_ACTIVATE_NEW_USERS is false but user still get logged in on register

### ISSUE THREAD

**Issue by remmar18** [nhost/nhost-js-sdk#75]
Hello,

Recently I stumbled upon a problem with the registry function from nhost SDK. When I register a user, it used too not automatically log me in because I sat AUTO_ACTIVATE_BASE USERS to false. But now when I use the same function, it gives the user a session even if it should be null. But after logging out and try logging in it will wait for activation.

Function:
```

  const registerUser = async () => {
          try {
              await auth.register({email, password, options: { userData: { display_name: email, avatar_url: "profile.png", first_name: "name", last_name: "last name" }, defaultRole: "user" }});
              console.log("User is registered")
          } catch (error) {
              console.error(error);
          }
  
      }
```

Any reason why this is happening?

**Comment by elitan** [comment]
@remmar18 Did you find a solution?

**Comment by remmar18** [comment]
@elitan Yeah, apparently "New Email Confirmation" was false for some reason. But after changing it back, it works again.
