### ISSUE TITLE
onAuthStateChanged Callback parameter

### ISSUE THREAD

**Issue by joshua1** [nhost/nhost-js-sdk#88]
using the nhost-js-sdk, when auth.login is called, an object is returned on successful login containing the Session, user, and MFA properties. This should be the same object returned as callback parameter for onAuthStateChanged function, as we apply the same logic in both cases (update user details in-store). Currently onAuthStateChange only returning a boolean value is only useful when that value is false. When Auth State changes, that State information what ever it is should be returned

**Comment by elitan** [comment]
I think that would make sense and we would be happy to accept such a PR.

In the meantime, would it be possible to use `auth.user()` when the auth state changes?
